### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Zombie Escape - Puzzle Path
email: contact.huydung@gmail.com
description: Escape the zombies by smashing smart, not hard
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cutezombies.fun" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#333'
twitter_username: huydung
github_username:  huydung
author: Cute Zombies Team
logo: assets/images/large-logo.png
twitter:
  username: huydung
social:
  name: Cute Zombies
  links:
    - https://twitter.com/huydung
    - https://www.facebook.com/huydung 146
    - https://www.linkedin.com/in/nguyenhuydung
#    - https://plus.google.com/+SandocheADITTANE
#    - https://github.com/sandoche

languages: ["en"]
ampdir: amp

github: https://github.com/huydung/cutezombies

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
